Updated to allow switching between different hosts
hpc-carpentry/hpc-shell pull request #13
Opened 2018-12-17 20:56 UTC by aturner-epcc

Added mechanics to allow switching between different remote hosts based on configuration options and code snippets. Based on work by @psteinb in hpc-in-a-day.

Configuration options added to _config.yml to define host properties and code snippets added in _includes directory.

README.md updated with brief description of how to configure lesson using the new options. 

Default is the configuration for Graham at Compute Canada so lesson is the same as before configuration changes. Example also included for Cirrus at EPCC.

2018-12-19 14:12 UTC, psteinb requested changes
Overall looks good, but I've discovered some rough edges from my point of view.

2018-12-19 14:12 UTC, psteinb commented on README.md
> +1. Follow the found in the [Software Carpentry example lesson source](https://github.com/carpentries/lesson-example/)
`Follow the found`?

2018-12-19 14:12 UTC, psteinb commented on _episodes/02-navigation.md
> +>   systems offer fast parallel file system access as a work file system. Typically, this will have
while it is correct, is it essential to indicate that we are talking about a **parallel** file system here?

2018-12-19 14:12 UTC, psteinb commented on _episodes/02-navigation.md
>  >   here is available throughout the HPC system and files stored here are backed up. Files stored
Are they always backed up? This can be a site specific configuration.

2018-12-19 14:12 UTC, psteinb commented on _episodes/02-navigation.md
> +>   higher performance than your home directory or network file system and will not usually be
backup strategies are site specific configurations. I wouldn't put them in the material. Instructors are free to comment on this when they present it.

2018-12-19 14:12 UTC, psteinb commented on _episodes/03-files.md
> +using a text editor. For this lesson, we are going to us `nano`, since it's more intuitive than many
shouldn't it be `going to use nano`?

2018-12-19 14:12 UTC, psteinb commented on _episodes/03-files.md
> +is relatively intuitive, and works for both files and directories `mv <file/directory> <path to new
I'd drop formulations like `is relatively intuitive`, as it could give people who don't immediately grasp `mv` mechanics a weird learning experience.

2018-12-19 14:12 UTC, psteinb commented on _episodes/03-files.md
> +> * `unrar` unzips .rar files (not available on many systems)
if it is not available on many systems, maybe we should rethink this callout. Further, `unzips .rar files` could be rephrased to `extracts the contents of .rar files` perhaps.

2018-12-20 19:33 UTC, ChristinaLK commented
I'm so excited to see this!!!  Thank you so so much @aturner-epcc !

2019-01-23 15:56 UTC, aturner-epcc commented
@psteinb I have addressed your comments in the latest commit. Are you happy for this PR to be merged now?

2019-01-23 16:09 UTC, psteinb approved these changes

2019-01-23 19:39 UTC, ChristinaLK commented
I don't have time to review, but I trust @psteinb review.  :)

2019-01-24 09:13 UTC, merged

2019-01-24 09:14 UTC, aturner-epcc commented
Thanks @psteinb!

2019-01-25 17:27 UTC, ChristinaLK commented
And thank YOU @aturner-epcc !!!